JCJOA/JCJ.OA.WebUI/Controllers/VideoInfoController.cs
using JCJ.OA.Model;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace JCJ.OA.WebUI.Controllers
{
    public class VideoInfoController : Controller
    {
        // GET: VidoFile
        IBLL.IVideoFileInfoService VideoFileInfoService { get; set; }
        IBLL.IVideoClassService VideoClassService { get; set; }
        public ActionResult Index()
        {
            return View();
        }
        /// <summary>
        /// 加载视频数据.
        /// </summary>
        /// <returns></returns>
        public ActionResult GetVideoInfo()
        {
            int pageIndex = Request["page"] != null ? int.Parse(Request["page"]) : 1;//当前页码。
            int pageSize = Request["rows"] != null ? int.Parse(Request["rows"]) : 5;
            int totalCount;
            var videoFileInfoList = VideoFileInfoService.LoadPageEntities<int>(pageIndex, pageSize, out totalCount, p => p.DelFlag == 0, p => p.ID, true);

            var temp = from p in videoFileInfoList
                       select new { ID = p.ID, Title = p.Title, AddDate = p.AddDate, Author = p.Author, Orgin = p.Orgin, ClassName = from c in p.VideoClass select c.ClassName };
            return Json(new { rows = temp, total = totalCount }, JsonRequestBehavior.AllowGet);
        }
        /// <summary>
        /// 展示添加视频的页面
        /// </summary>
        /// <returns></returns>
        public ActionResult ShowAddVideo()
        {
            var temp = VideoClassService.LoadEntities(a => a.DelFlag == 0).ToList();
            var videoClassList = from v in temp
                                 select new SelectListItem() { Text = v.ClassName, Value = v.ID.ToString() };
            ViewData["videoClass"] = videoClassList;
            return View();
        }
        /// <summary>
        /// 完成视频文件上传
        /// </summary>
        /// <returns></returns>
        public ActionResult VideoFileUp()
        {
            HttpPostedFileBase file = Request.Files["FileData"];
            string fileName = Path.GetFileName(file.FileName);
            string fileExt = Path.GetExtension(fileName);
            if (fileExt == ".avi")
            {
                string newFileName = Guid.NewGuid().ToString().Substring(0, 8);
                //将视频数据传递到视频转换服务器.
                WebClient webClient = new WebClient();
                webClient.UploadData("http://localhost:33242/VideoFileUp.ashx?fileName=" + newFileName + "&ext=" + fileExt, StreamToByte(file.InputStream));


                return Content("ok:视频上传成功!!" + ":" + newFileName);
            }
            return Content("no:视频上传错误!!");
        }

        private byte[] StreamToByte(Stream stream)
        {
            byte[] buffer = new byte[stream.Length];
            stream.Read(buffer, 0, buffer.Length);
            return buffer;
        }
        /// <summary>
        /// 接收从视频转换服务器发送过来的转换后的FLV视频。
        /// </summary>
        /// <returns></returns>
        public ActionResult GetVideoFile()
        {
            string fileName = Request["fileName"];
            string t = Request["t"];
            if (t == "flv")
            {
                using (FileStream fileStream = System.IO.File.OpenWrite(Request.MapPath("/Videos/Flv/" + fileName + ".flv")))
                {
                    Request.InputStream.CopyTo(fileStream);
                    return Content("ok");
                }
            }
            else
            {
                using (FileStream fileStream = System.IO.File.OpenWrite(Request.MapPath("/Videos/Flv/" + fileName + ".jpg")))
                {
                    Request.InputStream.CopyTo(fileStream);
                    return Content("ok");
                }
            }
        }
        /// <summary>
        /// 完成信息保存
        /// </summary>
        /// <param name="videoInfo"></param>
        /// <returns></returns>
        [ValidateInput(false)]
        public ActionResult AddVideo(VideoFileInfo videoInfo)
        {
            videoInfo.AddDate = DateTime.Now;
            videoInfo.DelFlag = 0;
            videoInfo.ImageUrl = "/Videos/Flv/" + Request["ImageUrl"] + ".jpg";
            videoInfo.ModifyDate = DateTime.Now;
            videoInfo.VideoPath = "/Videos/Flv/" + Request["ImageUrl"] + ".flv";
            int classId = int.Parse(Request["videoClass"]);
            return Content(VideoFileInfoService.AddVideoFileInfo(classId, videoInfo) ? "ok" : "no");
        }
        /// <summary>
        /// 播放视频
        /// </summary>
        /// <returns></returns>
        public ActionResult PlayVideo()
        {
            int id = int.Parse(Request["id"]);
            var videoInfo = VideoFileInfoService.LoadEntities(a => a.ID == id).FirstOrDefault();
            ViewBag.VideoInfo = videoInfo;
            return View();
        }
    }
}

JCJOA/JCJ.OA.WebUI/Views/VideoInfo/Index.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
    <link href="~/Content/themes/default/easyui.css" rel="stylesheet" />
    <link href="~/Content/themes/icon.css" rel="stylesheet" />
    <script src="~/Scripts/jquery-3.3.1.min.js"></script>
    <script src="~/Scripts/jquery.easyui.min.js"></script>
    <script src="~/Scripts/easyui-lang-zh_CN.js"></script>
    <script src="~/Scripts/datapattern.js"></script>
    <script src="~/Scripts/jquery.unobtrusive-ajax.min.js"></script>
    <script type="text/javascript">
        $(function () {
            $("#addDiv").css("display", "none");
            loadData();
        });
        function loadData() {
            $('#tt').datagrid({
                url: '/VideoInfo/GetVideoInfo',
                title: '视频数据表格',
                width: 700,
                height: 400,
                fitColumns: true, //列自适应
                nowrap: false,
                idField: 'ID',//主键列的列明
                loadMsg: '正在加载视频的信息...',
                pagination: true,//是否有分页
                singleSelect: false,//是否单行选择
                pageSize: 5,//页大小，一页多少条数据
                pageNumber: 1,//当前页，默认的
                pageList: [5, 10, 15],
                queryParams: {},//往后台传递参数
                columns: [[//c.UserName, c.UserPass, c.Email, c.RegTime
                    { field: 'ck', checkbox: true, align: 'left', width: 50 },
                    { field: 'ID', title: '编号', width: 80 },

                    { field: 'Title', title: '视频标题', width: 120 },
                    { field: 'Author', title: '视频作者', width: 120 },
                    { field: 'ClassName', title: '视频类别', width: 120 },
                    { field: 'Orgin', title: '视频来源', width: 120 },
                    {
                        field: 'AddDate', title: '时间', width: 80, align: 'right',
                        formatter: function (value, row, index) {
                            return (eval(value.replace(/\/Date\((\d+)\)\//gi, "new Date($1)"))).pattern("yyyy-M-d");
                        }
                    },

                    {
                        field: 'showDetail', title: '详细', width: 80, align: 'right',
                        formatter: function (value, row, index) {
                            var str = "<a href='javascript:void(0)' class='details' ids=" + row.ID + " >详细</a>";
                            return str;
                        }
                    }
                ]],
                toolbar: [{
                    id: 'btnDelete',
                    text: '删除',
                    iconCls: 'icon-remove',
                    handler: function () {


                    }
                }, {
                    id: 'btnAdd',
                    text: '添加',
                    iconCls: 'icon-add',
                    handler: function () {
                        addVideo();

                    }
                }, {
                    id: 'btnEdit',
                    text: '编辑',
                    iconCls: 'icon-edit',
                    handler: function () {

                    }
                }],
                onLoadSuccess: function () {
                    $(".details").click(function () {
                        var id = $(this).attr("ids");
                        var url = "/VideoInfo/ShowDetail?id=" + id;
                        window.open(url);
                    });

                }
            });
        }

        //添加视频
        function addVideo() {
            $("#addFrame").attr("src", "/VideoInfo/ShowAddVideo");
            $("#addDiv").css("display", "block");
            $('#addDiv').dialog({
                title: '添加视频信息',
                width: 900,
                height: 600,
                collapsible: true,
                maximizable: true,
                resizable: true,
                modal: true,
                buttons: [{
                    text: 'Ok',
                    iconCls: 'icon-ok',
                    handler: function () {
                        var childWindow = $("#addFrame")[0].contentWindow;
                        childWindow.subForm();
                    }
                }, {
                    text: 'Cancel',
                    handler: function () {
                        $('#addDiv').dialog('close');
                    }
                }]
            });
        }
        function afterAdd(data) {
            if (data == "ok") {
                $('#addDiv').dialog('close');
                $('#tt').datagrid('reload');
            } else {
                $.messager.alert("提示", "添加失败", "error");
            }
        }
    </script>
</head>
<body>
    <div>
        <table id="tt" style="width: 700px;" title="标题，可以使用代码进行初始化，也可以使用这种属性的方式" iconcls="icon-edit"></table>
    </div>
    <div>
        <iframe id="addFrame" width="100%" height="100%" frameborder="0"></iframe>
    </div>
</body>
</html>

JCJOA/JCJ.OA.WebUI/Views/VideoInfo/PlayVideo.cshtml
@{
    Layout = null;
}
@using JCJ.OA.Model
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>视频播放</title>
</head>
<body>
    @{
        VideoFileInfo videoFileInfo = ViewBag.VideoInfo;
    }
    <div>
        <h1>@videoFileInfo.Title</h1>
        <script src='/VideoPlay/AC_RunActiveContent.js' language='javascript'></script>
        <!-- saved from url=(0013)about:internet -->
        <script language='javascript'>
    AC_FL_RunContent('codebase', 'http://download.macromedia.com/pub/shockwave/cabs/flash/swflash.cab#version=9,0,0,0', 'width', '400', 'height', '325', 'src', ((!DetectFlashVer(9, 0, 0) && DetectFlashVer(8, 0, 0)) ? '/VideoPlay/OSplayer' : '/VideoPlay/OSplayer'), 'pluginspage', 'http://www.macromedia.com/go/getflashplayer', 'id', 'flvPlayer', 'allowFullScreen', 'true', 'allowScriptAccess', 'always', 'movie', ((!DetectFlashVer(9, 0, 0) && DetectFlashVer(8, 0, 0)) ? '/VideoPlay/OSplayer' : '/VideoPlay/OSplayer'), 'FlashVars', 'movie=@videoFileInfo.VideoPath&btncolor=0x333333&accentcolor=0x31b8e9&txtcolor=0xdddddd&volume=30&autoload=on&autoplay=off&vTitle=Super Mario Brothers Lego Edition&showTitle=yes');
        </script>
        <noscript>
            <object width='400' height='325' id='flvPlayer'>
                <param name='allowFullScreen' value='true'>
                <param name="allowScriptAccess" value="always">
                <param name='movie' value='/VideoPlay/OSplayer.swf?movie=@videoFileInfo.VideoPath&btncolor=0x333333&accentcolor=0x31b8e9&txtcolor=0xdddddd&volume=30&autoload=on&autoplay=off&vTitle=Super Mario Brothers Lego Edition&showTitle=yes'>
                <embed src='/VideoPlay/OSplayer.swf?movie=@videoFileInfo.VideoPath&btncolor=0x333333&accentcolor=0x31b8e9&txtcolor=0xdddddd&volume=30&autoload=on&autoplay=off&vTitle=Super Mario Brothers Lego Edition&showTitle=yes' width='400' height='325' allowFullScreen='true' type='application/x-shockwave-flash' allowScriptAccess='always'>
            </object>
        </noscript>

    </div>
</body>
</html>

JCJOA/JCJ.OA.WebUI/Views/VideoInfo/ShowAddVideo.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>ShowAddVideo</title>
    <link href="~/Content/themes/default/easyui.css" rel="stylesheet" />
    <script src="~/Scripts/jquery-3.3.1.min.js"></script>
    <script src="~/ckeditor/ckeditor.js"></script>
    <script src="/SwfUpload/swfupload.js"></script>
    <script src="/SwfUpload/handlers.js"></script>
    <script src="~/SwfUpload/swfupload.queue.js"></script>
    <script src="~/Scripts/jquery.unobtrusive-ajax.min.js"></script>
    <style type="text/css">
        textarea, select {
            padding: 2px;
            border: 1px solid;
            border-color: #666 #ccc #ccc #666;
            background: #F9F9F9;
            color: #333;
            resize: none;
            width: 100%;
        }

        .textbox {
            padding: 3px;
            border: 1px solid;
            border-color: #666 #ccc #ccc #666;
            background: #F9F9F9;
            color: #333;
            resize: none;
            width: 100%;
        }

            .textbox:hover, .textbox:focus, textarea:hover, textarea:focus {
                border-color: #09C;
                background: #F5F9FD;
            }

        div {
            display: block;
        }

            div.thumbshow {
                text-align: center;
                margin: 2px;
                padding: 2px;
                width: 162px;
                height: 150px;
                border: dashed 1px #B8B808;
                background: #FFFFF6;
                float: left;
            }
    </style>
    <script type="text/javascript">
          var swfu;
          window.onload = function () {
              swfu = new SWFUpload({
                  // Backend Settings
                  upload_url: "/VideoInfo/VideoFileUp",
                  post_params: {
                      "ASPSESSID": "@Session.SessionID"
                  },

                  // File Upload Settings
                  file_size_limit: "100 MB",
                  file_types: "*.avi;*.wmv",
                  file_types_description: "JPG Images",
                  file_upload_limit: 10,    // Zero means unlimited
                  file_queue_limit: 0,
                  // Event Handler Settings - these functions as defined in Handlers.js
                  //  The handlers are not part of SWFUpload but are part of my website and control how
                  //  my website reacts to the SWFUpload events.
                  swfupload_preload_handler: preLoad,
                  //file_queued_handler: fileQueued,
                  swfupload_load_failed_handler: loadFailed,

                  file_queue_error_handler: fileQueueError,
                  file_dialog_complete_handler: fileDialogComplete,
                  upload_progress_handler: uploadProgress,
                  upload_error_handler: uploadError,
                  upload_success_handler: showVideo,
                  upload_complete_handler: uploadComplete,

                  // Button settings
                  button_image_url: "/SWFUpload/images/XPButtonNoText_160x22.png",
                  button_placeholder_id: "spanButtonPlaceholder",
                  button_width: 160,
                  button_height: 22,
                  button_text: '<span class="button">请选择上传视频<span class="buttonSmall">(100 MB Max)</span></span>',
                  button_text_style: '.button { font-family: Helvetica, Arial, sans-serif; font-size: 14pt; } .buttonSmall { font-size: 10pt; }',
                  button_text_top_padding: 1,
                  button_text_left_padding: 5,

                  // Flash Settings
                  flash_url: "/SWFUpload/swfupload.swf",	// Relative to this file
                  flash9_url: "/SWFUpload/swfupload_FP9.swf",	// Relative to this file

                  custom_settings: {
                      upload_target: "divFileProgressContainer"
                  },

                  // Debug Settings
                  debug: false
              });
          }
          //上传成功以后执行
          function showVideo(file, serverData) {
              //将上传成功视频路径存储到隐藏域中。
              var data = serverData.split(':');
              if (data[0] == "ok") {
                  $("#txtVideoPath").val(data[1]);
                  $("#txtImageUrl").val(data[2]);
              } else {

              }
          }


          $(function () {
              $(".authorClick").click(function () {
                  var value = $(this).text();
                  $("#Author").val(value);
              });
              $(".originInfo").click(function () {
                  $("#Origin").val($(this).text());
              });
              //跟编辑器添加事件
              CKEDITOR.instances["VideoContent"].on("blur", function () {
                  //set keyup event
                  // this.document.on("keyup", getData2);
                  //and click event
                  //this.document.on("blur", getData2);
                  //and select event
                  //this.document.on("select", AutoSave);
                  getData2();
              });

          });

          //将编辑器的内容赋值给另外一个文本域
          function getData2() {
              var oEditor = CKEDITOR.instances.VideoContent;
              var data = oEditor.getData();
              $("#txtVideoContent").val(data);
          }

          //提交表单
          function subForm() {
              
              $("#addForm").submit();
          }

          //完成添加
          function afterAdd(data) {
              window.parent.afterAdd(data);
          }
    </script>
</head>
<body>
    <div>
        @using (Ajax.BeginForm("AddVideo", "VideoInfo", new AjaxOptions() { HttpMethod = "post", OnSuccess = "afterAdd" }, new { id = "addForm" }))
        {
            <input type="hidden" name="VideoPath" id="txtVideoPath" />
            <input type="hidden" name="ImageUrl" id="txtImageUrl" />
            <table style="width:auto; margin: 0 auto">
                <tr><td>视频名称：</td><td><input type="text" name="Title" class="textbox" /></td></tr>
                <tr><td>归属栏目:</td><td>@Html.DropDownList("videoClass")</td></tr>
                <tr><td>关 键 字</td><td><input type="text" name="KeyWords" class="textbox" /></td></tr>
                <tr><td>视频作者:</td><td><input type="text" name="Author" id="Author" class="textbox" />&nbsp;&nbsp;【<a href="javascript:void(0)" class="authorClick">未知</a>】【<a href="javascript:void(0)" class="authorClick">佚名</a>】【<a href="javascript:void(0)" class="authorClick">Itcast</a>】</td></tr>
                <tr><td>视频来源:</td><td><input type="text" name="Orgin" id="Origin" class="textbox" />&nbsp;&nbsp;【<a href="javascript:void(0)" class="originInfo">不详</a>】【<a href="javascript:void(0)" class="originInfo">本站原创</a>】【<a href="javascript:void(0)" class="originInfo">互联网</a>】</td></tr>

                <tr>
                    <td>视频内容:</td>
                    <td>
                        <div id="content">
                            <div id="swfu_container" style="margin: 0px 10px;">
                                <div>
                                    <span id="spanButtonPlaceholder">
                                    </span>
                                </div>
                                <div id="divFileProgressContainer" style="height: 45px;"></div>
                                <div class="fieldset flash" id="fsUploadProgress">
                                    <span class="legend">Upload Queue</span>
                                </div>
                                <div id="thumbnails">

                                </div>
                            </div>


                    </td>
                </tr>
                <tr>
                    <td>视频介绍:</td>
                    <td>
                        <textarea class="textbox" id="VideoContent" name="VideoContent1" rows="30" cols="40" style="width: 95%; height: 80px"></textarea>
                        <script type="text/javascript">
                            //<![CDATA[
                            // Replace the <textarea id="editor1"> with an CKEditor instance.
                            var editor = CKEDITOR.replace('VideoContent');
                                                  //]]>
                        </script>
                        <textarea class="textbox" name="VideoContent" id="txtVideoContent" rows="30" cols="40" style="display:none"></textarea>
                    </td>

                </tr>
            </table>

        }

    </div>
</body>
</html>