JCJOA/JCJ.OA.WebUI/Controllers/ArticelClassController.cs
using JCJ.OA.Model;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Web;
using System.Web.Mvc;

namespace JCJ.OA.WebUI.Controllers
{
    public class ArticelClassController : BaseController
    {
        // GET: ArticelClass
        IBLL.IArticelClassService ArticelClassService { get; set; }
        public ActionResult Index()
        {
            return View();
        }
        /// <summary>
        /// 获取根类别
        /// </summary>
        /// <returns></returns>
        public ActionResult ShowArticelClass() {
            var articeClassList = ArticelClassService.LoadEntities(a => a.ParentId == 0);
            var temp= from a in articeClassList
                      select new { id = a.ID, className = a.ClassName, Remark = a.Remark };
            return Json(temp, JsonRequestBehavior.AllowGet);
        }
        /// <summary>
        /// 获取子类别
        /// </summary>
        /// <returns></returns>
        public ActionResult ShowChildClass() {
            int id = int.Parse(Request["id"]);
            var articelClassList = ArticelClassService.LoadEntities(a => a.ParentId == id);
            var temp = from a in articelClassList
                       select new { id = a.ID, className = a.ClassName, Remark = a.Remark };
            return Json(temp, JsonRequestBehavior.AllowGet);
        }
        /// <summary>
        /// 展示创建类别
        /// </summary>
        /// <returns></returns>
        public ActionResult ShowAddClass() {
            int id = int.Parse(Request["cId"]);
            var articelParentClassList = ArticelClassService.LoadEntities(a => a.ParentId == 0);
            StringBuilder sb = new StringBuilder();
            foreach (var articelParentClass in articelParentClassList)
            {
                if (articelParentClass.ID == id)
                {
                    sb.Append("<option selected='selected' value='" + articelParentClass.ID + "'>" + "--" + articelParentClass.ClassName + "</option>");
                }
                else
                {
                    sb.Append("<option value='" + articelParentClass.ID + "'>" + "--" + articelParentClass.ClassName + "</option>");
                }
                var articelChildClassList = ArticelClassService.LoadEntities(a => a.ParentId == articelParentClass.ID);
                foreach (var childClass in articelChildClassList)
                {
                    if (childClass.ID == id)
                    {
                        sb.Append("<option selected='selected' value=" + childClass.ID + ">" + "----" + childClass.ClassName + "</option>");
                    }
                    else
                    {
                        sb.Append("<option value=" + childClass.ID + ">" + "----" + childClass.ClassName + "</option>");
                    }
                }
            }
            ViewBag.classInfo = sb.ToString();
            return View();
        }
        /// <summary>
        /// 添加类别
        /// </summary>
        /// <param name="articelClass"></param>
        /// <returns></returns>
        public ActionResult AddClass(ArticelClass articelClass)
        {
            articelClass.CreateUserId = LoginUser.ID;
            articelClass.CreateDate = DateTime.Now;
            articelClass.DelFlag = 0;
            ArticelClassService.AddEntity(articelClass);
            return Content("ok");
        }
    }
}

JCJOA/JCJ.OA.WebUI/Views/ArticelClass/Index.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>栏目管理</title>
    <link href="~/Content/themes/default/easyui.css" rel="stylesheet" />
    <link href="~/Content/themes/icon.css" rel="stylesheet" />
    <script src="~/Scripts/jquery-3.3.1.min.js"></script>
    <script src="~/Scripts/jquery.easyui.min.js"></script>
    <script src="~/Scripts/easyui-lang-zh_CN.js"></script>
    <script src="~/Scripts/datapattern.js"></script>
    <script type="text/javascript">
        $(function () {
            $("#addDiv").css("display", "none");
            loadData();
        });
        function loadData() {
            $('#tt').treegrid({
                url: '/ArticelClass/ShowArticelClass',
                title: '栏目管理',
                iconCls: 'icon-save',
                width: 500,
                height: 350,
                nowrap: false,
                rownumbers: true,
                animate: true,
                collapsible: true,
                idField: 'id',
                treeField: 'className',
                lines: true,
                columns: [[
                    { title: '编号', field: 'id', width: 150 },
                    { field: 'className', title: '栏目名称', width: 120, align: 'right' },
                    { field: 'Remark', title: '备注', width: 120 },
                ]],
                onClickRow: function (row) {
                    //根据所单击的行，获取对应的子类别.
                    $.post("/ArticelClass/ShowChildClass", { "id": row.id }, function (data) {
                        //先清空，后追加.如果没有数据不追加
                        if (data.length != 0) {
                            var nodes = $('#tt').treegrid('getChildren', row.id);
                            for (var i = 0; i < nodes.length; i++) {
                                $('#tt').treegrid('remove', nodes[i].id);
                            }
                            $('#tt').treegrid('append', {
                                parent: row.id,
                                data: data
                            });
                        }
                    });
                },
                toolbar: [{
                    id: 'btnAdd',
                    text: '添加子栏目',
                    iconCls: 'icon-add',
                    handler: function () {
                        addChildArticel();

                    }
                }, {
                    id: 'btnEdit',
                    text: '编辑',
                    iconCls: 'icon-edit',
                    handler: function () {
                        showChildArticel();

                    }
                }]
            });
        }
        //添加子类别
        function addChildArticel() {
            var row = $('#tt').treegrid('getSelected');
            if (row != null) {
                $("#addFrame").attr("src", "/ArticelClass/ShowAddClass?cId=" + row.id);
                $("addDiv").css("display", "block");
                $('#addDiv').dialog({
                    title: '完成新闻类别创建',
                    collapsible: true,
                    maximizable: true,
                    resizable: true,
                    modal: true,
                    width: 300,
                    height: 300,
                    buttons: [{
                        text: 'Ok',
                        iconCls: 'icon-ok',
                        handler: function () {
                            var childWindow = $("#addFrame")[0].contentWindow;
                            childWindow.subForm();

                        }
                    }, {
                        text: 'Cancel',
                        handler: function () {
                            $('#addDiv').dialog('close');

                        }
                    }]
                });
            } else {
                $.messager.alert("提示", "请选择对应的节点!!", "error");
            }
        }
        //添加完成后调用该方法.
        function afterAdd(data) {
            if (data == "ok") {
                $('#addDiv').dialog('close');
                $('#tt').treegrid('reload');
            }
        }
    </script>
</head>
<body>
    <div>
        <table id="tt" style="width:800px;height:500px"></table>
    </div>
    <div id="addDiv">
        <iframe id="addFrame" frameborder="0" width="100%" height="100%"></iframe>
    </div>
</body>
</html>

JCJOA/JCJ.OA.WebUI/Views/ArticelClass/ShowAddClass.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>添加类别</title>
    <link href="~/Content/tableStyle.css" rel="stylesheet" />
    <script src="~/Scripts/jquery-3.3.1.min.js"></script>
    <script src="~/Scripts/jquery.unobtrusive-ajax.min.js"></script>
    <script type="text/javascript">
        function subForm() {
            $("#addForm").submit();
        }
        function afterAdd(data) {
            window.parent.afterAdd(data);
        }
    </script>
</head>
<body>
    <div>
        @using (Ajax.BeginForm("addClass", "ArticelClass", new { }, new AjaxOptions() { HttpMethod = "post", OnSuccess = "afterAdd" }, new { id = "addForm" }))
        {
            <table>
                <tr>
                    <td>新闻类别</td>
                    <td>
                        <select name="ParentId">
                            <option value="0">根类别</option>
                            @MvcHtmlString.Create(ViewBag.classInfo)

                        </select>
                    </td>
                </tr>
                <tr><td>类别名称</td><td><input type="text" name="ClassName" /></td></tr>
                <tr><td>类别备注</td><td><input type="text" name="Remark" /></td></tr>
            </table>
        }
    </div>
</body>
</html>