JCJOA/JCJ.OA.WebUI/Controllers/ArticelInfoController.cs
using JCJ.OA.BLL;
using JCJ.OA.Common;
using JCJ.OA.Model;
using JCJ.OA.Model.Search;
using JCJ.OA.WebUI.Models;
using System;
using System.Collections.Generic;
using System.Drawing;
using System.IO;
using System.Linq;
using System.Text;
using System.Web;
using System.Web.Mvc;

namespace JCJ.OA.WebUI.Controllers
{
    public class ArticelInfoController : BaseController
    {
        // GET: ArticelInfo
        IBLL.IArticelClassService ArticelClassService { get; set; }
        IBLL.IArticelService ArticelService { get; set; }
        IBLL.ISensitiveWordService SensitiveWordService { get; set; }
        IBLL.IArticelCommentService ArticelCommentService { get; set; }
        public ActionResult Index()
        {
            ViewBag.classInfo = LoadArticelClassList();
            return View();
        }

        /// <summary>
        /// 加载新闻类别
        /// </summary>
        /// <returns></returns>
        private string LoadArticelClassList() {
            var articelParentClassList = ArticelClassService.LoadEntities(a => a.ParentId == 0);
            StringBuilder sb = new StringBuilder();
            foreach (var articelParentClass in articelParentClassList)
            {
                sb.Append("<option value='" + articelParentClass.ID + "'>" + "--" + articelParentClass.ClassName + "</option>");
                var articelChildClassList = ArticelClassService.LoadEntities(a => a.ParentId == articelParentClass.ID);
                foreach (var childClass in articelChildClassList)
                {
                    sb.Append("<option value=" + childClass.ID + ">" + "----" + childClass.ClassName + "</option>");
                }
            }
            return sb.ToString();
        }

        /// <summary>
        /// 搜索文章新闻
        /// </summary>
        /// <returns></returns>
        public ActionResult GetArticelInfo() {
            int pageIndex = Request["page"] != null ? int.Parse(Request["page"]) : 1;//当前页码。
            int pageSize = Request["rows"] != null ? int.Parse(Request["rows"]) : 5;//每页显示记录数。
            string fromDateTime = Request["formDatepicker"];
            string toDatepicker = Request["toDatepicker"];
            string articelClassId = Request["articelClassId"];
            string txtArticeTitle = Request["txtArticeTitle"];
            string txtArticelAuthor = Request["txtArticelAuthor"];
            int totalCount = 0;
            ArticelSearch articelSearch = new ArticelSearch()
            {
                ArticelAuthor = txtArticelAuthor,
                ArticelClassId = articelClassId,
                FormDatepicker = fromDateTime,
                ToDatepicker = toDatepicker,
                ArticelTitle = txtArticeTitle,
                PageIndex = pageIndex,
                PageSize = pageSize,
                TotalCount = totalCount

            };
            var articelList = ArticelService.LoadSearchEntities(articelSearch);
            var temp = from a in articelList
                       select new { ID = a.ID, Title = a.Title, Author = a.Author, AddDate = a.AddDate, Origin = a.Origin, ClassName = from c in a.ArticelClass select c.ClassName };

            return Json(new { rows = temp, total = articelSearch.TotalCount }, JsonRequestBehavior.AllowGet);
            
        }
        /// <summary>
        /// 展示添加新闻的表单
        /// </summary>
        /// <returns></returns>
        public ActionResult ShowAddInfo()
        {
            ViewBag.classInfo = LoadArticelClassList();
            return View();
        }
        /// <summary>
        /// 完成文件上传
        /// </summary>
        /// <returns></returns>
        public ActionResult FileUp()
        {
            HttpPostedFileBase file = Request.Files["Filedata"];
            if (file.ContentLength > 0)
            {
                string fileName = Path.GetFileName(file.FileName);
                string fileExt = Path.GetExtension(fileName);
                if (fileExt == ".jpg")
                {
                    string dir = "/ImageUp/" + DateTime.Now.Year + "/" + DateTime.Now.Month + "/" + DateTime.Now.Day + "/";
                    Directory.CreateDirectory(Path.GetDirectoryName(Request.MapPath(dir)));
                    string newfileName = Guid.NewGuid().ToString().Substring(0, 8);
                    string fullDir = dir + newfileName + fileExt;
                    string flag = Request["flag"];
                    if (!string.IsNullOrEmpty(flag))//表示添加水印
                    {
                        using (Image img = Image.FromStream(file.InputStream))
                        {
                            using (Bitmap map = new Bitmap(img.Width, img.Height))
                            {
                                using (Graphics g = Graphics.FromImage(map))
                                {
                                    g.DrawImage(img, 0, 0, map.Width, map.Height);
                                    g.DrawString("传智播客", new Font("微软雅黑", 14.0f, FontStyle.Bold), Brushes.Red, new PointF(map.Width - 60, map.Height - 30));
                                    map.Save(Request.MapPath(fullDir), System.Drawing.Imaging.ImageFormat.Jpeg);
                                    return Content("ok:" + fullDir);

                                }
                            }
                        }
                    }
                    else//表示不添加水印
                    {
                        file.SaveAs(Request.MapPath(fullDir));
                        return Content("ok:" + fullDir);
                    }
                }
                else
                {
                    return Content("no:格式错误!!");
                }
            }
            else
            {
                return Content("no:请选择上传的文件");
            }
        }

        /// <summary>
        /// 完成文章新闻添加
        /// </summary>
        /// <param name="articelInfo"></param>
        /// <returns></returns>
        [ValidateInput(false)]//不对发送给该方法的HTML内容作安全检查
        [HttpPost]
        public ActionResult AddArticelInfo(Articel articelInfo)
        {
            articelInfo.AddDate = DateTime.Now;
            articelInfo.DelFlag = 0;
            articelInfo.ModifyDate = DateTime.Now;
            int cid = int.Parse(Request["ArticelClassInfo"]);
            ArticelService.AddEntity(cid, articelInfo);
            //完成内容保存以后，生成静态页面
            CreateHtmlPage(articelInfo, "add");
            //将新添加的文章写到队列中并且存储到Lucene.Net中
            SearchContent searchContent = new SearchContent();
            searchContent.Content = articelInfo.ArticleContent;
            searchContent.Id = articelInfo.ID;
            searchContent.Flag = 0;
            searchContent.AddDate = articelInfo.AddDate;
            searchContent.Title = articelInfo.Title;
            IndexManager.GetInstance().AddEqueue(searchContent);
            return Content("ok");
        }
        /// <summary>
        /// 展示要编辑的新闻
        /// </summary>
        /// <returns></returns>
        public ActionResult ShowEditInfo()
        {
            int id = int.Parse(Request["id"]);
            var articelInfo = ArticelService.LoadEntities(a => a.ID == id).FirstOrDefault();
            ViewBag.ArticelInfo = articelInfo;
            return View();
        }
        /// <summary>
        /// 获取根类别信息，填充Tree
        /// </summary>
        /// <returns></returns>
        public ActionResult GetArticelClass()
        {
            var articelClassList = ArticelClassService.LoadEntities(a => a.ParentId == 0);
            var temp = from a in articelClassList
                       select new { id = a.ID, text = a.ClassName };
            return Json(temp, JsonRequestBehavior.AllowGet);
        }

        /// <summary>
        /// 查找子类别，并且将文章所属的类别前面的复选框选中
        /// </summary>
        /// <returns></returns>
        public ActionResult ShowChildClass()
        {
            int classId = int.Parse(Request["classId"]);//父类别编号
            int articelId = int.Parse(Request["articelId"]);//文章编号
                                                            //找出父类下的子类
            var childClassList = ArticelClassService.LoadEntities(a => a.ParentId == classId);
            //获取文章的类别。
            var articelInfo = ArticelService.LoadEntities(a => a.ID == articelId).FirstOrDefault();
            var articelClassList = from a in articelInfo.ArticelClass
                                   select a.ID;
            List<ArticelClassModel> list = new List<ArticelClassModel>();
            foreach (var childClass in childClassList)
            {
                if (articelClassList.Contains(childClass.ID))
                {
                    ArticelClassModel articelClassModel = new ArticelClassModel();
                    articelClassModel.Checked = true;
                    articelClassModel.Id = childClass.ID;
                    articelClassModel.Text = childClass.ClassName;
                    list.Add(articelClassModel);
                }
                else
                {
                    ArticelClassModel articelClassModel = new ArticelClassModel();
                    articelClassModel.Id = childClass.ID;
                    articelClassModel.Text = childClass.ClassName;
                    list.Add(articelClassModel);
                }
            }
            var temp = from a in list
                       select new { id = a.Id, text = a.Text, @checked = a.Checked };
            return Json(temp, JsonRequestBehavior.AllowGet);

        }
        /// <summary>
        /// 完成文章类别的修改
        /// </summary>
        /// <returns></returns>
        public ActionResult EditArticelClass()
        {
            string classId = Request["classId"];
            string[] classIds = classId.Split(',');
            int articelId = int.Parse(Request["articelId"]);
            List<int> list = new List<int>();
            foreach (string cid in classIds)
            {
                list.Add(Convert.ToInt32(cid));
            }

JCJOA/JCJ.OA.WebUI/Views/ArticelInfo/ShowAddInfo.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>添加新闻</title>
    <link href="~/Content/tableStyle.css" rel="stylesheet" />
    <script src="~/ckeditor/ckeditor.js"></script>
    <script src="/SwfUpload/swfupload.js"></script>
    <script src="/SwfUpload/handlers.js"></script>
    <script src="~/Scripts/jquery-3.3.1.min.js"></script>
    <script src="~/Scripts/jquery.unobtrusive-ajax.min.js"></script>
    <style type="text/css">
        textarea, select {
            padding: 2px;
            border: 1px solid;
            border-color: #666 #ccc #ccc #666;
            background: #F9F9F9;
            color: #333;
            resize: none;
            width: 100%;
        }

        .textbox {
            padding: 3px;
            border: 1px solid;
            border-color: #666 #ccc #ccc #666;
            background: #F9F9F9;
            color: #333;
            resize: none;
            width: 100%;
        }

            .textbox:hover, .textbox:focus, textarea:hover, textarea:focus {
                border-color: #09C;
                background: #F5F9FD;
            }
    </style>
    <script type="text/javascript">
        var swfu;
        window.onload = function () {
            swfu = new SWFUpload({
                // Backend Settings
                upload_url: "/ArticelInfo/FileUp",
                post_params: {
                    "ASPSESSID": "@Session.SessionID"
                },

                // File Upload Settings
                file_size_limit: "2 MB",
                file_types: "*.jpg",
                file_types_description: "JPG Images",
                file_upload_limit: 0,    // Zero means unlimited

                // Event Handler Settings - these functions as defined in Handlers.js
                //  The handlers are not part of SWFUpload but are part of my website and control how
                //  my website reacts to the SWFUpload events.
                swfupload_preload_handler: preLoad,
                swfupload_load_failed_handler: loadFailed,
                file_queue_error_handler: fileQueueError,
                file_dialog_complete_handler: fileDialogComplete,
                upload_progress_handler: uploadProgress,
                upload_error_handler: uploadError,
                upload_success_handler: uploadOk,
                upload_complete_handler: uploadComplete,
                upload_start_handler: uploadStart,
                // Button settings
                button_image_url: "/SWFUpload/images/XPButtonNoText_160x22.png",
                button_placeholder_id: "spanButtonPlaceholder",
                button_width: 160,
                button_height: 22,
                button_text: '<span class="button">Select Images <span class="buttonSmall">(2 MB Max)</span></span>',
                button_text_style: '.button { font-family: Helvetica, Arial, sans-serif; font-size: 14pt; } .buttonSmall { font-size: 10pt; }',
                button_text_top_padding: 1,
                button_text_left_padding: 5,

                // Flash Settings
                flash_url: "/SWFUpload/swfupload.swf",	// Relative to this file
                flash9_url: "/SWFUpload/swfupload_FP9.swf",	// Relative to this file

                custom_settings: {
                    upload_target: "divFileProgressContainer"
                },

                // Debug Settings
                debug: false
            });
        }
        //上传之前。
        function uploadStart() {
            var flag = $("#AddWaterFlag").is(":checked");
            if (flag) {
                swfu.setPostParams({ "flag": 1 });
                swfu.startUpload();//继续上传
            }
        }
        //上传成功以后
        function uploadOk(file, serverData) {
            var data = serverData.split(':');
            if (data[0] == "ok") {
                $("#imgSrc").attr("src", data[1]);
                $("#PhotoUrl").val(data[1]);
                //判断是否选择了"图片是否插入编辑器"
                var flag = $("#InsertEditContent").is(":checked");
                if (flag) {
                    var oEditor = CKEDITOR.instances.ArticleContent;//找到编辑器
                    if (oEditor.mode == 'wysiwyg') {//what you see is what you get  所见即所得
                        var img = "<img src='"+data[1]+"'/>";
                            oEditor.insertHtml(img);//将上传成功的图片插入到编辑器中。
                    }
                    else
                        alert('You must be in WYSIWYG mode!');

                }
            } else {
                alert(data[0]);
            }
        }
        $(function () {
            //添加作者
            $(".authorClick").click(function () {
                $("#Author").val($(this).text());
            });
            //添加原创
            $(".originInfo").click(function () {
                $("#Origin").val($(this).text());
            });
            //给编辑绑定一个事件。
            CKEDITOR.instances["ArticleContent"].on("blur", function () {
                //获取编辑器内容。
                var oEditor = CKEDITOR.instances.ArticleContent;
                var content = oEditor.getData();
                $("#txtArticleContent").val(content);

            });
        });
        //提交表单。、
        function subForm() {
            $("#addFomr").submit();
        }
        //提交完成后
        function afterAdd(data) {
            window.parent.afterAdd(data);
        }
    </script>
</head>
<body>
    <div>
        @using (Ajax.BeginForm("AddArticelInfo", "ArticelInfo", new { }, new AjaxOptions() { HttpMethod = "post", OnSuccess = "afterAdd" }, new { id = "addFomr" }))
        {
            <table style="width:auto; margin: 0 auto">
                <tr>
                    <td>简短标题:</td>
                    <td>
                        <select name="TitleType" id="TitleType">
                            <option></option>
                            <option style="color: green">[图文]</option>
                            <option style="color: red">[组图]</option>
                            <option style="color: #990000">[推荐]</option>
                            <option style="color: #0000FF">[注意]</option>
                            <option style="color: blue">[公告]</option>
                        </select>
                    </td>
                    <td>
                        <input type="text" name="title" maxlength="160" class="textbox" id="title" />
                    </td>
                    <td>
                        <select name="TitleFontType" id="TitleFontType">
                            <option value="0">字形</option>
                            <option value="1">粗体</option>
                            <option value="2">斜体</option>
                            <option value="3">粗+斜</option>
                            <option value="0">规则</option>
                        </select>
                    </td>
                    <td>
                        <select name="TitleFontColor" id="TitleFontColor">
                            <option value="0">颜色</option>
                            <option value="1">红色</option>
                            <option value="2">蓝色</option>
                            <option value="3">绿色</option>

                        </select>
                    </td>
                </tr>
                <tr>
                    <td>完整标题:</td>
                    <td colspan="4">
                        <input type="text" name="Fulltitle" class="textbox" id="Fulltitle" />
                    </td>
                </tr>
                <tr>
                    <td>归属栏目:</td>
                    <td colspan="4">
                        <select name="ArticelClassInfo" id="ArticelClassInfo">
                            <option value="">--请选择归属栏目--</option>
                            @MvcHtmlString.Create(ViewBag.classInfo)
                        </select>
                    </td>
                </tr>
                <tr>
                    <td>关 键 字</td>
                    <td colspan="4">
                        <input type="text" name="KeyWords" class="textbox" id="KeyWords" />
                    </td>
                </tr>
                <tr>
                    <td>文章作者:</td>
                    <td colspan="4">
                        <input type="text" name="Author" class="textbox" id="Author" />&nbsp;&nbsp;【<a href="javascript:void(0)" class="authorClick">未知</a>】【<a href="javascript:void(0)" class="authorClick">佚名</a>】【<a href="javascript:void(0)" class="authorClick">Itcast</a>】
                    </td>
                </tr>
                <tr>
                    <td>文章来源:</td>
                    <td colspan="4">
                        <input name="Origin" id="Origin" value="" size="50" class="textbox" type="text">&nbsp;&nbsp;【<a href="javascript:void(0)" class="originInfo">不详</a>】【<a href="javascript:void(0)" class="originInfo">本站原创</a>】【<a href="javascript:void(0)" class="originInfo">互联网</a>】
                    </td>
                </tr>
                <tr>
                    <td>文章导读</td>
                    <td colspan="4">
                        <textarea class="textbox" name="Intro" style="width: 95%; height: 80px"></textarea>
                    </td>
                </tr>
                <tr>
                    <td>文章内容</td>
                    <td colspan="4">
                        <textarea class="textbox" onblur="getData2()" id="ArticleContent" name="ArticleContent1" rows="30" cols="40" style="width: 95%; height: 80px"></textarea>
                        <script type="text/javascript">
                            //<![CDATA[
                            // Replace the <textarea id="editor1"> with an CKEditor instance.
                            var editor = CKEDITOR.replace('ArticleContent');
                                                  //]]>
    </script>
    <textarea class="textbox" name="ArticleContent" id="txtArticleContent" rows="30" cols="40" style="display:none"></textarea>
    </td>
    </tr>
    <tr>
        <td>图片地址:</td>
        <td colspan="4">
            <div id="content">
                <div id="swfu_container" style="margin: 0px 10px;">
                    <div>
                        <span id="spanButtonPlaceholder"></span>
                    </div>
                    <div id="divFileProgressContainer" style="height: 45px;"></div>
                    <div id="thumbnails"></div>
                    <img id="imgSrc" width="50px" height="50px" />
                </div>
            </div>


            <input name="PhotoUrl" id="PhotoUrl" value="" type="hidden">
            <input name="AddWaterFlag" id="AddWaterFlag" value="1" type="checkbox">添加水印
            <input name="InsertEditContent" id="InsertEditContent" value="1" type="checkbox">图片是否插入编辑器
        </td>
    </tr>
    </table>
}

    </div>
</body>
</html>