JCJOA/JCJ.OA.WebUI/Controllers/ActionInfoController.cs
using JCJ.OA.Model;
using JCJ.OA.Model.Enum;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace JCJ.OA.WebUI.Controllers
{
    public class ActionInfoController : Controller
    {
        IBLL.IActionInfoService ActionInfoService { get; set; }
        // GET: ActionInfo
        public ActionResult Index()
        {
            return View();
        }

        /// <summary>
        /// 获得权限信息
        /// </summary>
        /// <returns></returns>
        public ActionResult GetActionInfo()
        {
            int pageIndex = Request["page"] != null ? int.Parse(Request["page"]) : 1;
            int pageSize = Request["rows"] != null ? int.Parse(Request["rows"]) : 5;
            int totalCount;
            short delFlag = (short)DelFlagEnum.Normal;
            var actionInfoList = ActionInfoService.LoadPageEntities<int>(pageIndex, pageSize, out totalCount, a => a.DelFlag == delFlag, a => a.ID, true);
            var temp = from a in actionInfoList
                       select new
                       {
                           a.ID,
                           a.ActionInfoName,
                           a.ActionTypeEnum,
                           a.HttpMethod, 
                           a.Url,
                           a.Remark,
                           a.SubTime,
                           a.Sort
                       };
            return Json(new { rows = temp, total = totalCount }, JsonRequestBehavior.AllowGet);
        }
        /// <summary>
        /// 上传文件
        /// </summary>
        /// <returns></returns>
        public ActionResult FileUpload()
        {
            HttpPostedFileBase file = Request.Files[0];
            string fileName = Path.GetFileName(file.FileName);
            string fileExt = Path.GetExtension(fileName);
            if (fileExt == ".jpg")
            {
                string dir = "/ImageUp/" + DateTime.Now.Year + "/" + DateTime.Now.Month + "/" + DateTime.Now.Day + "/";
                Directory.CreateDirectory(Path.GetDirectoryName(Request.MapPath(dir)));
                string newfileName = Guid.NewGuid().ToString();
                string fullDir = dir + newfileName + fileExt;
                file.SaveAs(Request.MapPath(fullDir));
                return Content("ok:" + fullDir);
            }
            return Content("no:上传失败!!");
        }
        /// <summary>
        /// 完成权限添加
        /// </summary>
        /// <param name="actionInfo"></param>
        /// <returns></returns>
        public ActionResult AddActionInfo(ActionInfo actionInfo)
        {
            actionInfo.DelFlag = 0;
            actionInfo.ModifiedOn = DateTime.Now.ToString();
            actionInfo.SubTime = DateTime.Now;
            actionInfo.Url = actionInfo.Url.ToLower();
            ActionInfoService.AddEntity(actionInfo);
            return Content("ok");
        }
    }
}

JCJOA/JCJ.OA.WebUI/Views/ActionInfo/Index.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>权限信息</title>
    <link href="~/Content/themes/default/easyui.css" rel="stylesheet" />
    <link href="~/Content/themes/icon.css" rel="stylesheet" />
    <script src="~/Scripts/jquery-3.3.1.min.js"></script>
    <script src="~/Scripts/jquery.easyui.min.js"></script>
    <script src="~/Scripts/easyui-lang-zh_CN.js"></script>
    <script src="~/Scripts/jquery.unobtrusive-ajax.min.js"></script>
    <script src="~/Scripts/jquery.validate.min.js"></script>
    <script src="~/Scripts/datapattern.js"></script>
    <script type="text/javascript">
        $(function () {
            $("#addDiv").css("display", "none");
            loadData();
            bindActionTypeChange();
            bindBtnFileUpClick();
        });
        function loadData() {
            $('#tt').datagrid({
                url: '/ActionInfo/GetActionInfo',
                title: '权限数据表格',
                width: 700,
                height: 400,
                fitColumns: true, //列自适应
                nowrap: false,
                idField: 'ID',//主键列的列明
                loadMsg: '正在加载权限的信息...',
                pagination: true,//是否有分页
                singleSelect: false,//是否单行选择
                pageSize: 5,//页大小，一页多少条数据
                pageNumber: 1,//当前页，默认的
                pageList: [5, 10, 15],
                queryParams: {},//往后台传递参数
                columns: [[//c.UserName, c.UserPass, c.Email, c.RegTime
                    { field: 'ck', checkbox: true, align: 'left', width: 50 },
                    { field: 'ID', title: '编号', width: 80 },
                    { field: 'ActionInfoName', title: '权限名称', width: 120 },
                    {
                        field: 'ActionTypeEnum', title: '权限类型', width: 120,
                        formatter: function (value, row, index) {
                            return value == "1" ? "菜单权限" : "普通权限";
                        }
                    },
                    { field: 'Url', title: 'Url', width: 120 },
                    { field: 'HttpMethod', title: 'HttpMethod', width: 120 },
                    { field: 'Sort', title: '排序', width: 120 },
                    { field: 'Remark', title: '备注', width: 120 },
                    {
                        field: 'SubTime', title: '时间', width: 80, align: 'right',
                        formatter: function (value, row, index) {
                            return (eval(value.replace(/\/Date\((\d+)\)\//gi, "new Date($1)"))).pattern("yyyy-M-d");
                        }
                    },
                    {
                        field: 'showDetail', title: '详细', width: 80, align: 'right',
                        formatter: function (value, row, index) {
                            var str = "<a href='javascript:void(0)' class='details' ids='"+row.ID+"'>详细</a>";
                            return str;
                        }
                    }
                ]],
                onLoadSuccess: function (data) {
                    $('.details').click(function () {
                        alert($(this).attr("ids"));
                    })
                },
                toolbar: [{
                    id: 'btnDelete',
                    text: '删除',
                    iconCls: 'icon-remove',
                    handler: function () {

                    }

                }, {
                    id: 'btnAdd',
                    text: '添加',
                    iconCls: 'icon-add',
                    handler: function () {
                        addAction();
                    }
                }, {
                    id: 'btnEdit',
                    text: '编辑',
                    iconCls: 'icon-edit',
                    handler: function () {

                    }
                }
                ],
            });
        }
        //给权限类别下拉框绑定change事件
        function bindActionTypeChange() {
            $("#actionTypeChange").change(function () {
                if ($(this).val() == "1") {//菜单权限
                    $("#trIcon").fadeIn();
                } else {
                    $("#trIcon").fadeOut();
                }
            });
        }
        //上传按钮单击
        function bindBtnFileUpClick() {
            $("#btnFileUp").click(function () {
                $("#addForm").ajaxSubmit({
                    success: function (data) {
                        var serverData = data.split(':');
                        if (serverData[0] == "ok") {
                            $("#showImg").html("<img src='" + serverData[1] + "' width='50px' height='50px'/>");
                            $("#hiddenMenuIcon").val(serverData[1]);
                        } else {
                            $.messager.alert("提示", serverData[1], "error");
                        }
                    },
                    error: function (error) { alert(error); },
                    url: '/ActionInfo/FileUpload', /*设置post提交到的页面*/
                    type: "post", /*设置表单以post方法提交*/
                    dataType: "text" /*设置返回值类型为文本*/
                });
            });
        }
        //添加权限
        function addAction() {
            $("#addDiv").css("display", "block");
            $('#addDiv').dialog({
                title: '添加权限信息',
                collapsible: true,
                maximizable: true,
                resizable: true,
                modal: true,
                width: 300,
                height: 300,
                buttons: [{
                    text: 'Ok',
                    iconCls: 'icon-ok',
                    handler: function () {

                        $("#addForm").submit();//提交
                    }
                }, {
                    text: 'Cancel',
                    handler: function () {
                        $('#addDiv').dialog('close');

                    }
                }]
            });
        }
        //添加完成后执行
        function afterAdd(data) {
            if (data == "ok") {
                $('#addDiv').dialog('close');
            } else {
                $.messager.alert("提示", "添加失败", "error");
            }
        }
    </script>
</head>
<body>
    <div>
        <table id="tt" style="width: 700px;" title="标题，可以使用代码进行初始化，也可以使用这种属性的方式" iconcls="icon-edit"></table>
    </div>
    <div id="addDiv">
        @using (Ajax.BeginForm("AddActionInfo", "ActionInfo", new { }, new AjaxOptions() { HttpMethod = "post", OnSuccess = "afterAdd" }, new { id = "addForm" }))
        {
            <input type="hidden" name="MenuIcon" id="hiddenMenuIcon" />
            <table>
                <tr><td>权限名称</td><td><input type="text" name="ActionInfoName" /></td></tr>
                <tr><td>Url</td><td><input type="text" name="Url" /></td></tr>
                <tr>
                    <td>HttpMethod</td>
                    <td>
                        <select name="HttpMethod">
                            <option value="GET">Get</option>
                            <option value="POST">Post</option>
                        </select>
                    </td>
                </tr>
                <tr>
                    <td>权限类型</td>
                    <td>
                        <select name="ActionTypeEnum" id="actionTypeChange">
                            <option value="0">普通权限</option>
                            <option value="1">菜单权限</option>
                        </select>
                    </td>
                </tr>
                <tr style="display:none" id="trIcon">
                    <td>上传图标</td>
                    <td>
                        <input type="file" name="fileUp" />
                        <input type="button" value="上传" id="btnFileUp" />
                        <div id="showImg">

                        </div>
                    </td>
                </tr>

                <tr><td>备注</td><td><input type="text" name="Remark" /></td></tr>
                <tr><td>排序</td><td><input type="text" name="Sort" /></td></tr>
            </table>
        }
    </div>
</body>
</html>